site_name: Software-Defined Camera
#site_url: ''
#use_directory_urls: false

extra_css: 
    - extra.css

theme:
    name: readthedocs
    max_width: 2000
    navigation_depth: 5
    features:
        - content.code.copy
        - content.code.annotate
    #name: windmill

nav:
    - Concept:
        - General              : index.md 
        - Video Link Protocol  : video-link-proto.md
    - Environment:
        - Dependencies         : deps.md
        - Tools                : tools.md
        - Host                 : host.md
    - Implementation:
        - Architecture         : arch.md
        - High Level           : high-level.md
        - Low  Level           : low-level.md
        - Remote Control API   : rc-api.md


extra_javascript:
    - js/mathjax.js
    - js/mathjax/tex-mml-chtml.js
    - js/wavedrom.min.js
    - js/wavedrom_loader.js
    - js/wavedrom.unpkg.js
    - js/wavedrom_skin_default.js


markdown_extensions:
    - toc:
        permalink: "🔗"
        baselevel: 1
    - pymdownx.arithmatex:
       generic: true    
    - admonition
    - attr_list
    - footnotes
    - markdown_wavedrom
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.blocks.caption
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets

plugins:
    - search:
        lang: ru

    - glightbox
    #- markdownwavedrom
