site_name: Software-Defined Camera
#site_url: ''
#use_directory_urls: false

extra_css: [extra.css]

theme:
    name: readthedocs
    max_width: 2000
    features:
        - content.code.copy
        - content.code.annotate     
  # name: windmill

nav:
    - Concept:
        - General              : index.md 
        - Video Link Protocol  : video-link-proto.md
    - Environment:
        - Dependencies         : deps.md
        - Tools                : tools.md
    - Implementation:
        - Architecture         : arch.md
        - Low  Level           : low-level.md
        - High Level           : high-level.md


extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/2.6.8/wavedrom.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/2.6.8/skins/default.js
    - js/wavedrom_loader.js
    - https://cdn.jsdelivr.net/npm/wavedrom@2.1.2/wavedrom.unpkg.js
    - https://wavedrom.com/skins/default.js

markdown_extensions:
    - toc:
        permalink: "🔗"
        baselevel: 1
    - mdx_math
    - admonition
    - attr_list
    - footnotes
    - markdown_wavedrom
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true

plugins:
    - search:
        lang: ru

    - glightbox
    #- markdownwavedrom
